### ISSUE TITLE
Module expects a file to be present on repeated runs and causes error

### ISSUE THREAD

**Issue by mrshah-at-work** [cloud-native-toolkit/terraform-ibm-vpe-gateway#12]
if `.tmp` folder with its contents is deleted or moved, it fails to run `terraform plan` after applied. This also causes failure of `terraform apply` or `terraform destroy`.

This happens because once the resource (VPE gateway) is created, the module expects the file to be present on consequent runs.

The error received is:

```
Error: open /tmp/ra-vsi-base-pattern/terraform/pattern/.tmp/endpoint-gateway-targets.json: no such file or directory
```

**Comment by seansund** [comment]
Fixed in [cloud-native-toolkit/terraform-ibm-vpe-gateway#v1.3.0](https://github.com/cloud-native-toolkit/terraform-ibm-vpe-gateway/releases/tag/v1.3.0)

**Comment by mrshah-at-work** [comment]
@seansund I tested the fix, it does not fix the issue. Can we reopen the issue?

**Comment by seansund** [comment]
I think this may be related to a change made in terraform v13 - https://github.com/hashicorp/terraform/issues/25463 . Will try v14 to see if it is fixed as the issue suggests
